### PR TITLE
dependencies: Remove usage of srcd.works

### LINKED ISSUE #99: Remove usage of obsolete package "srcd.works/go-errors.v0"
CI has failed due to srcd.works not existing anymore: https://travis-ci.org/bblfsh/server/builds/273847022
It should be replaced by `gopkg.in/src-d/go-errors.v0`

### PR DESCRIPTION
**Pull request by abeaumont**
Fixes #99

### CODE REVIEW

File: cmd/bblfsh/client.go [hunk 1]
```diff
@@ -15,7 +15,7 @@ import (
 	"github.com/Sirupsen/logrus"
 	"google.golang.org/grpc"
 	"gopkg.in/bblfsh/sdk.v0/protocol"
-	"srcd.works/go-errors.v0"
+	"gopkg.in/src-d/go-errors.v0"
```
Comment (juanjux) [inline cmd/bblfsh/client.go]: Just wanted to comment that there is a `v1` too, linking to `v1.0.0`, I'm not sure if we must use `v0`.

Comment (abeaumont) [reply cmd/bblfsh/client.go]: The reason for using `v0` is that we are already using it in other parts of the repo, but looking at the difference betweent the two, there are none, so I'll upgrade to `v1`.

**Comment by abeaumont** [comment]
Upgraded to v1
